services:
    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: php
        volumes:
            - .:/var/www/html
            - php_vendor:/var/www/html/vendor
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            DB_HOST: mysql
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        command: >
            sh -c ".docker/wait-for-it.sh mysql:3306 -- php artisan migrate && php-fpm"
        networks:
            - concord_test_network

    node:
        build:
            context: .
            dockerfile: .docker/node/Dockerfile
        container_name: node
        volumes:
            - .:/var/www/html
            - node_modules:/var/www/html/node_modules
        working_dir: /var/www/html
        ports:
            - "5173:5173"
        networks:
            - concord_test_network

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - node
        networks:
            - concord_test_network

    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - concord_test_network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}" ]
            interval: 10s
            timeout: 10s
            retries: 40

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - mysql
        networks:
            - concord_test_network

volumes:
    dbdata:
    php_vendor:
    node_modules:

networks:
    concord_test_network:
        driver: bridge
